### ISSUE TITLE
/etc/sudoers/amd-indicator-sudoers breaks system

### ISSUE THREAD

**Issue by benow** [fredldotme/amd-indicator#5]
There's a problem in amd-indicator-sudoers which prevents sudo from running:
$ sudo su
sudo: >>> /etc/sudoers.d/amd-indicator-sudoers: syntax error near line 1 <<<
sudo: parse error in /etc/sudoers.d/amd-indicator-sudoers near line 1
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

No sudo and no root login means I can't delete or fix.  A boot into single mode is required.  Not good.

**Comment by benow** [comment]
For others encountering this, I was able to edit the amd-indicator-sudoers without single user mode via 'pkexec bash'.

The problem is in the file is the lack of a trailing newline, it seems.

**Comment by Sadi58** [comment]
I've added a trailing new line now as suggested. Can you confirm if it's OK now? For I'm not using amd/intel hybrid graphics card at the moment.
