### ISSUE TITLE
Doesn't switch

### ISSUE THREAD

**Issue by htrex** [fredldotme/amd-indicator#6]
I've installed amd-indicator as per instruction and I can see it's icon on the top bar.
Clicking "Quick switch graphics processor" shows the dialog, clicking ok reboots my laptop, but after login I can see both from amd-indicator and from amdccle that the active GPU is always the integrated Intel.

Switching GPU between integrated Intel and discrete AMD 6770M works fine with amdccle.

I'm on a fresh Ubuntu 14.04 install using fglrx-updates from repo trusty/restricted.

Please let me know if you need additional infos.

**Comment by Sadi58** [comment]
Can you open the Terminal, enter the following command and tell us the terminal output:
sudo amdconfig --px-dgpu
Normally this command should do the switching, which should then be applied after a reboot.
If this manual method works, then we should check the sudoers I guess.

**Comment by htrex** [comment]
I've done some more tests and found that:
- switching from discrete to integrated GPU works nicely with amd-indicator while it doesn't work from integrated to discrete.
- amdcccle works perfectly to switch between the two on both sides

while running on _integrated GPU_ `/usr/local/indicator-amd/dgpuon` reports

```
amdconfig: No supported adapters detected
pkill: killing pid 1249 failed: Operation not permitted
reboot: Need to be root
```

while running on _discrete GPU_ `/usr/local/indicator-amd/dgpuon` reports

```
/usr/local/indicator-amd/dgpuon
PowerXpress: This option must be run as root  !
pkill: killing pid 1250 failed: Operation not permitted
reboot: Need to be root
```

while on integrated GPU `sudo amdconfig --px-dgpu` reports

```
amdconfig: No supported adapters detected
```

so we've found the problem, that's a bug of amdconfig!
It should allow the switch between integrated and discrete from the command line while it fails to detect the discrete GPU when it's not active.

Can you please tell me which fglrx version are you using?

**Comment by Sadi58** [comment]
I'm now on Ubuntu 14.04 without hybrid graphics, but last time I used this indicator on Ubuntu 13.10 upon installing the AMD driver as suggested here: http://askubuntu.com/questions/205112/how-do-i-get-amd-intel-hybrid-graphics-drivers-to-work

The solution suggested there for Ubuntu 13.10 was the following:
sudo apt-get install fglrx fglrx-pxpress

**Comment by htrex** [comment]
fglrx-pxpress still exists on Ubuntu 14.04 but it's just a dummy package, with a dependency to ubuntu-drivers-common and this description:
"This is a transitional package for ubuntu-drivers-common. You can remove it after upgrading." 

Looking at fglrx package content seems that pxpress has been merged directly there.
This seems mostly a bug of amd-config that is working one way only (from discrete to integrated), as for some reason it doesn't recognize the AMD GPU and refuses to work.

It's not clear to me how amdcccle switches without problem, maybe it uses something  other to trigger the switch.
