### ISSUE TITLE
Intel icon size

### ISSUE THREAD

**Issue by picccard** [fredldotme/amd-indicator#7]
Intel icon is oversized in gnome fallback compiz, but is nice and small in Unity. Fix this please

**Comment by Sadi58** [comment]
I have now drastically reduced image sizes (height=48px) and hope gnome fallback session can manage to adjust them to its panel size.

**Comment by picccard** [comment]
![intel_gnome_fallback](https://cloud.githubusercontent.com/assets/7443949/2844222/099ebb68-d088-11e3-8f3b-ad9fa20ea487.png)

The icon got much smaller now, but it isn't displayed as it is in Unity:

![intel_unity](https://cloud.githubusercontent.com/assets/7443949/2844223/09a6ee00-d088-11e3-89ba-258d11f111a4.png)

**Comment by Sadi58** [comment]
Reduced to 22px high now, although intel images are a bit too wide. I hope it looks OK on both panels now.

**Comment by picccard** [comment]
The result is as good as perfect, Thanks!
