### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by picccard** [fredldotme/amd-indicator#8]
I get this error and i dont understand it, can someone tell me what the message means? The indicator works perfectly, but the error is annoying me. Using trusty.

![libgl_error](https://cloud.githubusercontent.com/assets/7443949/2855528/91acb958-d15d-11e3-877f-e05bce7b6261.png)

**Comment by Sadi58** [comment]
I no longer have amd/intel hybrid graphics like beidl, so I personally cannot help with this project any more I think, but your problem might be related with the fglrx package itself, and it might even be one of those minor error messages which appear when you launch this or that application from the terminal, which you normally don't see at GUI level.

**Comment by picccard** [comment]
But what is the top bar suppose to show? What is it's purpose?

**Comment by Sadi58** [comment]
During the period I've used this indicator, I've never seen such an error message. It merely displayed  "Using: Xxxxxxxxx" which shows the exact name of the display driver version in use.

**Comment by logich** [comment]
This is an error that is shown from glxinfo. You can fix it by creating a symlink to the real intel dri library. I think it is a problem with the ubuntu-drivers-common package not making the link. -Logan

**Comment by picccard** [comment]
Thank you logich!

Managed to go to hide the error from the indicator with this workaround.

For others with the same error (or another error you want to hide) I did the following:

`sudo gedit /usr/local/bin/amd-indicator`

Search (Ctrl+F)
`OpenGL renderer string`

Where the file says:

``` ruby
def rendererString(self):
    stat, out = commands.getstatusoutput('glxinfo | grep "OpenGL renderer string"')
    out = out.replace("OpenGL renderer string", "Using")
    return out
```

Add a new out = out.replce before the first one with the content you want to remove
Then if should look like this:

``` ruby
def rendererString(self):
    stat, out = commands.getstatusoutput('glxinfo | grep "OpenGL renderer string"')
    out = out.replace("libGL error: dlopen /usr/lib/fglrx/dri/i965_dri.so failed (/usr/lib/fglrx/dri/i965_dri.so: cannot open shared object file: No such file or directory)", "")
    out = out.replace("OpenGL renderer string", "Using")
    return out
```

The resault was the following:

![indicator_fixed](https://cloud.githubusercontent.com/assets/7443949/2921004/ecbdace0-d6ed-11e3-827d-8f5269a7d09c.png)

OPTIONAL:

The same editing could be done in the "amd-indicator" file in you amd-indicator folder before installing.

**Comment by Sadi58** [comment]
IMHO this fix shouldn't be included in the source code of amd-indicator.
Also I think it will be better if somebody else could take over / fork this project as neither beidl nor myself have this amd/intel hybrid graphics any longer.

**Comment by bkeane** [comment]
Your opinion is correct on not including this fix. Erasing an error message is not correcting an error. Logan is correct in his solution though, I confirmed.
1. locate your i965_dri.so file (found it with 'locate i965_dri.so')
2. create a symlink with full paths from where you found i965_dri.so, to the folder that appears in the error message to begin with. Use full paths in your ln -s command, otherwise you will get another error.

**Comment by picccard** [comment]
Instead of hiding the error i did this:

Open terminal and locate the missing file
`locate i965_dri.so`

The output of this command was a folder, I opened this folder via the terminal with sudo
`sudo nautilus /usr/lib/x86_64-linux-gnu/dri/i965_dri.so`

In that folder the  missing file was, I copied the actual file to the location it was missing from with
`sudo su cp /usr/lib/x86_64-linux-gnu/dri/i965_dri.so > /usr/lib/fglrx/dri/i965_dri.so`

After restarting the error was gone! Much better way!

**Comment by bkeane** [comment]
Props for a Nautilus path man. Always should be provided.
